
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-UCSBOrganization-EditPage","number":105,"title":"Edit Page for UCSBOrganization plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-2/pull/105"},{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-UCSBOrganization-IndexPage","number":104,"title":"Added Index Page for \"UCSBOrganization\" plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-2/pull/104"},{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-UCSBOrganization-CreatePage","number":102,"title":"Added Create Page for \"UCSBOrganization\" plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-2/pull/102"},{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-UCSBOrganization-Pages","number":101,"title":"Added UCSBOrganization placeholders","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-2/pull/101"}]
